# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Tagging.create(taggable_type: "Band", taggable_id: 2, tag_id: 1)
Tagging.create(taggable_type: "Band", taggable_id: 2, tag_id: 2)
Tagging.create(taggable_type: "Band", taggable_id: 1, tag_id: 3)
Tagging.create(taggable_type: "Band", taggable_id: 1, tag_id: 4)

Tagging.create(taggable_type: "Album", taggable_id: 4, tag_id: 1)
Tagging.create(taggable_type: "Album", taggable_id: 4, tag_id: 2)
Tagging.create(taggable_type: "Album", taggable_id: 4, tag_id: 3)
Tagging.create(taggable_type: "Album", taggable_id: 4, tag_id: 4)
Tagging.create(taggable_type: "Album", taggable_id: 3, tag_id: 2)
Tagging.create(taggable_type: "Album", taggable_id: 3, tag_id: 3)
Tagging.create(taggable_type: "Album", taggable_id: 3, tag_id: 4)
Tagging.create(taggable_type: "Album", taggable_id: 2, tag_id: 3)
Tagging.create(taggable_type: "Album", taggable_id: 2, tag_id: 4)
Tagging.create(taggable_type: "Album", taggable_id: 1, tag_id: 4)

Tagging.create(taggable_type: "Track", taggable_id: 8, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 8, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 8, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 8, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 7, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 7, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 7, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 7, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 6, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 6, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 6, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 6, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 5, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 5, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 5, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 5, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 4, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 4, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 4, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 4, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 3, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 3, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 3, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 3, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 2, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 2, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 2, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 2, tag_id: 1)
Tagging.create(taggable_type: "Track", taggable_id: 1, tag_id: 4)
Tagging.create(taggable_type: "Track", taggable_id: 1, tag_id: 3)
Tagging.create(taggable_type: "Track", taggable_id: 1, tag_id: 2)
Tagging.create(taggable_type: "Track", taggable_id: 1, tag_id: 1)
